In [1]:
import edgar
import pandas as pd

In [3]:
#edgar.download_index('C:\\Users\\tulki\\OneDrive\\Desktop\\Professional Development', 2018, skip_all_present_except_last=False)

In [22]:
selectedcompany = 'Alphabet Inc.'
selectedreport = '10-Q'

In [23]:
csv = pd.read_csv('2019-QTR4.tsv', sep='/t', lineterminator = '\n', names= None)
csv.columns.values[0] = 'Item'
companyreport = csv[(csv['Item'].str.contains(selectedcompany)) & (csv['Item'].str.contains(selectedreport))]

filing = companyreport['Item'].str.split('|')
filing = filing.to_list()

for item in filing[0]:
    if 'html' in item:
        report = item   
        
url = 'https://www.sec.gov/Archives/' + report#[0:-1]

df = pd.read_html(url)
doc_index = df[0]
doc_index = doc_index.dropna()
doc_name = doc_index[doc_index['Description'].str.contains(selectedreport)]
doc_name = doc_name['Document'].str.split(' ')
doc_name = doc_name[0][0]
doc_name

url = url.replace('-', '')
url = url.replace('index.html', '')
url = url +'/' + doc_name

df = pd.read_html(url)
for item in df:
    bs = (item[0].str.contains('Retained') | item[0].str.contains('Total Assets'))
    if bs.any():
        balance_sheet = item

balance_sheet = balance_sheet.iloc[2:, [0,2,6]]
header = balance_sheet.iloc[0]
balance_sheet = balance_sheet[1:]
balance_sheet.columns = header

balance_sheet.columns.values[0] = 'Item'
balance_sheet[balance_sheet.columns[1:]] = balance_sheet[balance_sheet.columns[1:]].astype(str)
balance_sheet[balance_sheet.columns[1]] = balance_sheet[balance_sheet.columns[1]].map(lambda x: x.replace('(', '-'))
balance_sheet[balance_sheet.columns[2]] = balance_sheet[balance_sheet.columns[2]].map(lambda x: x.replace('(', '-'))
balance_sheet[balance_sheet.columns[1]] = balance_sheet[balance_sheet.columns[1]].map(lambda x: x.replace(',', ''))
balance_sheet[balance_sheet.columns[2]] = balance_sheet[balance_sheet.columns[2]].map(lambda x: x.replace(',', ''))

balance_sheet = balance_sheet[3:]
balance_sheet[balance_sheet.columns[1:]] = balance_sheet[balance_sheet.columns[1:]].astype(float)
balance_sheet

C:\Users\tulki\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

2,Item,"As of December 31, 2018","As ofSeptember 30, 2019"
6,Cash and cash equivalents,16701.0,16032.0
7,Marketable securities,92439.0,105145.0
8,"Total cash, cash equivalents, and marketable s...",109140.0,121177.0
9,"Accounts receivable, net of allowance of $729 ...",20838.0,20889.0
10,"Income taxes receivable, net",355.0,192.0
11,Inventory,1107.0,1401.0
12,Other current assets,4236.0,4699.0
13,Total current assets,135676.0,148358.0
14,Non-marketable investments,13859.0,12488.0
15,Deferred income taxes,737.0,564.0
16,"Property and equipment, net",59719.0,69252.0
17,Operating lease assets,0.0,10341.0
18,"Intangible assets, net",2220.0,1747.0
19,Goodwill,17888.0,18069.0
20,Other non-current assets,2693.0,2225.0
21,Total assets,232792.0,263044.0
22,Liabilities and Stockholders’ Equity,NaN,NaN
23,Current liabilities:,NaN,NaN
24,Accounts payable,4378.0,4142.0
25,Accrued compensation and benefits,6839.0,7399.0
26,Accrued expenses and other current liabilities,16958.0,21038.0
27,Accrued revenue share,4592.0,4835.0
28,Deferred revenue,1784.0,1679.0
29,"Income taxes payable, net",69.0,131.0
30,Total current liabilities,34620.0,39224.0
31,Long-term debt,4012.0,4082.0
32,"Deferred revenue, non-current",396.0,364.0
33,"Income taxes payable, non-current",11327.0,11355.0
34,Deferred income taxes,1264.0,1747.0
35,Operating lease liabilities,0.0,9666.0
36,Other long-term liabilities,3545.0,1637.0
37,Total liabilities,55164.0,68075.0
38,Commitments and Contingencies (Note 10),NaN,NaN
39,Stockholders’ equity:,NaN,NaN
40,"Convertible preferred stock, $0.001 par value ...",0.0,0.0
41,"Class A and Class B common stock, and Class C ...",45049.0,49040.0
42,Accumulated other comprehensive loss,-2306.0,-1196.0
43,Retained earnings,134885.0,147125.0
44,Total stockholders’ equity,177628.0,194969.0
45,Total liabilities and stockholders’ equity,232792.0,263044.0